<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Security Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 13px;
            color: #333;
            margin: 30px;
        }
        .header {
            text-align: center;
            background-color: #1a202c;
            color: white;
            padding: 20px;
            border-radius: 8px;
            margin-bottom: 20px;
        }
        .header h1 { margin: 0; font-size: 22px; }
        .header p  { margin: 5px 0 0; font-size: 13px; }
        .section {
            margin-bottom: 20px;
            border: 1px solid #e2e8f0;
            border-radius: 6px;
            padding: 15px;
        }
        .section h2 {
            margin: 0 0 10px;
            font-size: 15px;
            border-bottom: 2px solid #e2e8f0;
            padding-bottom: 8px;
            color: #2d3748;
        }
        .risk-high   { color: #e53e3e; font-weight: bold; }
        .risk-medium { color: #dd6b20; font-weight: bold; }
        .risk-low    { color: #38a169; font-weight: bold; }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 8px;
        }
        th {
            background: #f7fafc;
            padding: 8px;
            text-align: left;
            font-size: 12px;
            border: 1px solid #e2e8f0;
        }
        td {
            padding: 7px 8px;
            border: 1px solid #e2e8f0;
            font-size: 12px;
        }
        .score-box {
            display: inline-block;
            padding: 10px 20px;
            border-radius: 6px;
            font-size: 28px;
            font-weight: bold;
            margin: 10px 0;
        }
        .footer {
            text-align: center;
            margin-top: 30px;
            font-size: 11px;
            color: #718096;
        }
    </style>
</head>
<body>

    {{-- Header --}}
    <div class="header">
        <h1>🔐 Cybersecurity Awareness Report</h1>
        <p>Generated for: {{ $user['name'] }} | {{ $generated_at }}</p>
    </div>

    {{-- Risk Score --}}
    <div class="section">
        <h2>📊 Overall Risk Score</h2>
        @if($risk_score)
            <div class="score-box
                @if($risk_score['level'] === 'high') risk-high
                @elseif($risk_score['level'] === 'medium') risk-medium
                @else risk-low @endif">
                {{ $risk_score['score'] }} / 100
            </div>
            <p>Risk Level:
                <span class="risk-{{ $risk_score['level'] }}">
                    {{ strtoupper($risk_score['level']) }}
                </span>
            </p>
        @else
            <p>No risk score generated yet.</p>
        @endif
    </div>

    {{-- Quiz Results --}}
    <div class="section">
        <h2>📝 Quiz Performance</h2>
        <table>
            <tr>
                <th>Total Quizzes Taken</th>
                <th>Average Score</th>
                <th>Highest Score</th>
            </tr>
            <tr>
                <td>{{ $quiz_summary['total_taken'] }}</td>
                <td>{{ $quiz_summary['average_score'] }}%</td>
                <td>{{ $quiz_summary['highest_score'] }}%</td>
            </tr>
        </table>
    </div>

    {{-- Scan Activity --}}
    <div class="section">
        <h2>🔍 Phishing Scan Activity</h2>
        <table>
            <tr>
                <th>Total Scans</th>
                <th>High Risk</th>
                <th>Medium Risk</th>
                <th>Low Risk</th>
            </tr>
            <tr>
                <td>{{ $scan_summary['total_scans'] }}</td>
                <td class="risk-high">{{ $scan_summary['high_risk'] }}</td>
                <td class="risk-medium">{{ $scan_summary['medium_risk'] }}</td>
                <td class="risk-low">{{ $scan_summary['low_risk'] }}</td>
            </tr>
        </table>
    </div>

    {{-- Lesson Progress --}}
    <div class="section">
        <h2>📚 Lesson Progress</h2>
        <table>
            <tr>
                <th>Completed Lessons</th>
                <th>In Progress</th>
            </tr>
            <tr>
                <td>{{ $lesson_summary['total_completed'] }}</td>
                <td>{{ $lesson_summary['in_progress'] }}</td>
            </tr>
        </table>
    </div>

    {{-- Recommendations --}}
    <div class="section">
        <h2>💡 Security Recommendations</h2>
        @foreach($recommendations as $tip)
        <p>
            <strong>{{ $loop->iteration }}. {{ $tip['title'] }}</strong><br>
            {{ $tip['description'] }}
        </p>
        @endforeach
    </div>

    {{-- Footer --}}
    <div class="footer">
        <p>This report was automatically generated by the Cybersecurity Awareness Platform.</p>
        <p>{{ $generated_at }}</p>
    </div>

</body>
</html>
